import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.scss'
import Header from '@/components/header'
import Task from '@/components/task-list-set/task-list/task'
import TaskList from '@/components/task-list-set/task-list'

const inter = Inter({ subsets: ['latin'] })

export const StatusOptions = {
  UNFINISHED: 'Unfinished',
  INPROGRESS: 'In progress',
  REVIEWING: 'Reviewing',
  DONE: 'Done',
};

const issueOne = {description: "finished the thing I was working on", status: StatusOptions.UNFINISHED, id: 1, index: 0};
const issueTwo = {description: "made it through to gym today", status: StatusOptions.UNFINISHED, id: 2, index: 1};
const issueThree = {description: "ate a lot of great food, but I'm focused on working it off", status: StatusOptions.UNFINISHED, id: 3, index: 2};
const issueFour = {description: "stuff", status: StatusOptions.UNFINISHED, id: 4, index: 3};
const issues = {tasks: [issueOne, issueTwo, issueThree, issueFour], status: StatusOptions.UNFINISHED}
//ideal payload:
// issue = {description, date, status}

export default function Home() {
  return (
    <div className={inter.className}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <main className={`${styles.main}`}>
        <TaskList {...issues}></TaskList>
      </main>
    </div>
  );
}
